version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/startlens
      - ./log_data:/startlens/log
    tty: true
    stdin_open: true
    command: ["uwsgi", "--http", "0.0.0.0:3000", "--wsgi-file", "app/controllers/webserver.py", "--callable", "app"]