version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/startlens
      - ./log_data:/startlens/log
    tty: true
    stdin_open: true
    command: /bin/bash