apiVersion: v1
kind: Service
metadata:
  name: learning-lb
  namespace: webapp
spec:
  type: LoadBalancer
  selector:
    app: learning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000